name: ci

on:
  pull_request:
    branches: [ master ]
    
jobs:
  ci_to_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm install
      # latest angular-devkit/build-angular to erase the warnings packages.
      - run: npm install @angular-devkit/build-angular
      - run: npm i @actions/core
      - run: npm i @actions/github
      - run: node index.js
      - run: npm run lint

# git rev-parse master es como puedo ver el ultimo commit en master ya sea successfull o no
