name: ci

on:
  pull_request:
    branches: [ master ]
    
jobs:
  ci_to_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-artifact@main
        with:
          name: artifact
