name: ci

on:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - uses: actions/jekyll-build-pages@v1
      - run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .
      - uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./docs/artifact.tar
  report-build-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
        name: Report build status
