name: ci

on:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm install
      # - run: mkdir -p docs/${{ github.event.number }}
      - run: npm run build
      - uses: actions/jekyll-build-pages@v1
        name: Build page with Jekkyl
      - run: tar --dereference --hard-dereference --directory docs/ -cvf artifact.tar .
        name: Archive build output
      - uses: actions/upload-artifact@main
        name: Upload Artifact
        with:
          name: github-pages
          path: ./artifact.tar
  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v1
        name: Report build status
        with:
          emit_telemetry: true
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: github-pages
    permissions:
      id-token: write
      pull-requests: write
      pages: write
      contents: read
    steps:
      - uses: actions/deploy-pages@v1
        name: Deploy to Github github-pages
        with:
          emit_telemetry: false
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
